language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: PHPCS=1
  allow_failures:
    - php: 7.0
    - php: hhvm-nightly

install:
- composer self-update
- composer install --prefer-dist --no-interaction

before_script:
  - sh -c "if [ '$PHPCS' = '1' ]; then composer require cakephp/cakephp-codesniffer:~2.0; fi"
  - phpenv rehash

script:
  - sh -c "if [ '$PHPCS' != '1' ]; then phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php,css,js --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config ./webroot --ignore=.src/Template/Bake,./webroot/css/base.css,./webroot/css/cdn-fallback,./webroot/js/cdn-fallback; fi"

notifications:
  email: false
