language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - composer require 'cakephp/cakephp-codesniffer:~2.0'
  - phpenv rehash

script:
  vendor/bin/phpcs -p --extensions=php,css,js --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config ./webroot --ignore=./webroot/css/base.css,./webroot/css/cdn-fallback,./webroot/js/cdn-fallback

notifications:
  email: false
